---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
spec:
  selector:
    matchLabels:
      app: loginapp
  replicas: 2
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
      - name: loginapp
        image: {{ .Values.images.name }}:{{ .Values.images.version }}
        ports:
        - containerPort: 3000
